export const CURRENT_USER = "CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN = "LOGIN";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_USER = "REGISTER_USER";

export const GET_EMAIL = "GET_EMAIL";
export const GET_EMAIL_SUCCESS = "GET_EMAIL_SUCCESS";
export const GET_EMAIL_FAIL = "GET_EMAIL_FAIL";

export const GET_GOOGLE = "GET_GOOGLE";
export const GET_GOOGLE_SUCCESS = "GET_GOOGLE_SUCCESS";
export const GET_GOOGLE_FAIL = "GET_GOOGLE_FAIL";

export const GET_FACEBOOK = "GET_FACEBOOK";
export const GET_FACEBOOK_SUCCESS = "GET_FACEBOOK_SUCCESS";
export const GET_FACEBOOK_FAIL = "GET_FACEBOOK_FAIL";

export const SELECT_NOTE = "SELECT_NOTE";