export const CURRENT_USER = "CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN = "LOGIN";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_USER = "REGISTER_USER";

export const GET_EMAIL = "GET_EMAIL";
export const GET_EMAIL_SUCCESS = "GET_EMAIL_SUCCESS";
export const GET_EMAIL_FAIL = "GET_EMAIL_FAIL";

export const GET_GOOGLE = "GET_GOOGLE";
export const GET_GOOGLE_SUCCESS = "GET_GOOGLE_SUCCESS";
export const GET_GOOGLE_FAIL = "GET_GOOGLE_FAIL";

export const GET_FACEBOOK = "GET_FACEBOOK";
export const GET_FACEBOOK_SUCCESS = "GET_FACEBOOK_SUCCESS";
export const GET_FACEBOOK_FAIL = "GET_FACEBOOK_FAIL";

export const OPEN_NOTE = "OPEN_NOTE";
export const CREATE_NEW_NOTE = "CREATE_NEW_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const UPDATE_NOTE_LIST = "UPDATE_NOTE_LIST";
export const UPDATE_SELECTED_NOTE = "UPDATE_SELECTED_NOTE";
export const CLEAR_SELECTED_NOTE = "CLEAR_SELECTED_NOTE";
export const EDIT_NOTE_ITEM = "EDIT_NOTE_ITEM";
export const EDIT_NOTE_TITLE = "EDIT_NOTE_TITLE";
export const EDIT_NOTE_CONTENT = "EDIT_NOTE_CONTENT";
export const TOGGLE_PIN = "TOGGLE_PIN";
