const CURRENT_USER = "CURRENT_USER";
const GET_GOOGLE = "GET_GOOGLE";
const GET_GOOGLE_SUCCESS = "GET_GOOGLE_SUCCESS";
const GET_GOOGLE_FAIL = "GET_GOOGLE_FAIL";
const GET_FACEBOOK = "GET_FACEBOOK";
const GET_FACEBOOK_SUCCESS = "GET_FACEBOOK_SUCCESS";
const GET_FACEBOOK_FAIL = "GET_FACEBOOK_FAIL";
const LOGOUT_USER = "LOGOUT_USER";

const SWATCH = {
    WHITE: "white",

    BLACK: "black",

    GRAY: "gray",

    RED: "red",

    LIGHT_GRAY: "lightgray",
};

const LAYOUT_MARGIN = 17;

export {
    SWATCH,
    LAYOUT_MARGIN,
    CURRENT_USER,
    GET_GOOGLE,
    GET_GOOGLE_SUCCESS,
    GET_GOOGLE_FAIL,
    GET_FACEBOOK,
    GET_FACEBOOK_FAIL,
    GET_FACEBOOK_SUCCESS,
    LOGOUT_USER,
};
